// this file was mostly generated by AI

import { describe, it, expect, vi, beforeAll, beforeEach } from 'vitest';
import request from 'supertest';

vi.mock('../../config/database', () => ({
  prisma: {
    user: {
      findUnique: vi.fn(),
      create: vi.fn(),
    },
  },
}));

import { prisma } from '../../config/database';
import app from '../../app';

const findUnique = vi.mocked(prisma.user.findUnique);
const create = vi.mocked(prisma.user.create);

const VALID_BODY = {
  email: 'test@example.com',
  username: 'testuser',
  password: 'password123',
};

const CREATED_USER = {
  id: 1,
  email: VALID_BODY.email,
  username: VALID_BODY.username,
  password: 'hashed',
};

beforeAll(() => {
  process.env.JWT_SECRET = 'test-secret-that-is-long-enough-for-jwt';
});

beforeEach(() => {
  vi.clearAllMocks();
});

describe('POST /api/auth/register', () => {
  describe('successful registration', () => {
    it('returns 201 with user data and sets a cookie', async () => {
      findUnique.mockResolvedValue(null);
      create.mockResolvedValue(CREATED_USER as never);

      const res = await request(app)
        .post('/api/auth/register')
        .send(VALID_BODY);

      expect(res.status).toBe(201);
      expect(res.body).toEqual({
        success: true,
        data: { id: 1, email: VALID_BODY.email, username: VALID_BODY.username },
      });
      expect(res.headers['set-cookie']).toBeDefined();
    });

    it('does not expose the password hash in the response', async () => {
      findUnique.mockResolvedValue(null);
      create.mockResolvedValue(CREATED_USER as never);

      const res = await request(app)
        .post('/api/auth/register')
        .send({ email: 'a@b.com' });

      expect(res.status).toBe(400);
      expect(res.body.success).toBe(false);
    });

    it('returns 400 for an invalid email format', async () => {
      const res = await request(app)
        .post('/api/auth/register')
        .send({ ...VALID_BODY, email: 'not-an-email' });

      expect(res.status).toBe(400);
      expect(res.body.error).toMatch(/invalid email/i);
    });

    it('returns 400 when password is shorter than 8 characters', async () => {
      const res = await request(app)
        .post('/api/auth/register')
        .send({ ...VALID_BODY, password: 'short' });

      expect(res.status).toBe(400);
      expect(res.body.error).toMatch(/8 characters/i);
    });
  });

  describe('duplicate email', () => {
    it('returns 409 when the email is already registered', async () => {
      findUnique.mockResolvedValue(CREATED_USER as never);

      const res = await request(app).post('/api/auth/register').send(VALID_BODY);

      expect(res.status).toBe(409);
      expect(res.body.error).toMatch(/already in use/i);
    });
  });
});
