// these tests were mostly generated by AI

import { describe, it, expect, vi, beforeAll, beforeEach } from 'vitest';
import request from 'supertest';
import jwt from 'jsonwebtoken';

vi.mock('../../config/database', () => ({
  prisma: {
    $transaction: vi.fn(),
    ranking: {
      findUnique: vi.fn(),
      delete: vi.fn(),
    },
  },
}));

vi.mock('../../services/rankingAnalysisResolver', () => ({
  invalidateRankingAnalysisCache: vi.fn(),
  getRankingAnalysisForYear: vi.fn(),
}));

vi.mock('../../services/rankings', () => ({
  getMyRankingsResponse: vi.fn(),
}));

import { prisma } from '../../config/database';
import { invalidateRankingAnalysisCache } from '../../services/rankingAnalysisResolver';
import app from '../../app';

const JWT_SECRET = 'test-secret-that-is-long-enough-for-jwt';
const USER_ID = 1;
const YEAR = 2024;

const ENTRIES_PAYLOAD = [
  { entryId: 1, position: 0 },
  { entryId: 2, position: 1 },
];

const SAVED_RANKING = { id: 42, year: YEAR, entries: ENTRIES_PAYLOAD };

beforeAll(() => {
  process.env.JWT_SECRET = JWT_SECRET;
});

beforeEach(() => {
  vi.clearAllMocks();
});

const authCookie = () => {
  const token = jwt.sign({ sub: USER_ID }, JWT_SECRET, { expiresIn: '7d' });
  return `token=${token}`;
};

const mockTransaction = () => {
  const tx = {
    ranking: {
      upsert: vi.fn().mockResolvedValue({ id: 42, userId: USER_ID, year: YEAR }),
      findUnique: vi.fn().mockResolvedValue(SAVED_RANKING),
    },
    rankingEntry: {
      deleteMany: vi.fn().mockResolvedValue({ count: 0 }),
      createMany: vi.fn().mockResolvedValue({ count: 2 }),
    },
  };
  vi.mocked(prisma.$transaction).mockImplementation(
    ((cb: (tx: unknown) => Promise<unknown>) => cb(tx)) as never
  );
};

describe('GET /api/rankings/:year', () => {
  it('returns 401 without a cookie', async () => {
    const res = await request(app).get(`/api/rankings/${YEAR}`);
    expect(res.status).toBe(401);
  });

  it('returns entries when a ranking exists', async () => {
    vi.mocked(prisma.ranking.findUnique).mockResolvedValue(SAVED_RANKING as never);

    const res = await request(app)
      .get(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie());

    expect(res.status).toBe(200);
    expect(res.body.data.entries).toEqual(ENTRIES_PAYLOAD);
  });

  it('returns empty entries when no ranking exists yet', async () => {
    vi.mocked(prisma.ranking.findUnique).mockResolvedValue(null);

    const res = await request(app)
      .get(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie());

    expect(res.status).toBe(200);
    expect(res.body.data.entries).toEqual([]);
  });
});

describe('PUT /api/rankings/:year', () => {
  it('returns 401 without a cookie', async () => {
    const res = await request(app)
      .put(`/api/rankings/${YEAR}`)
      .send({ entries: ENTRIES_PAYLOAD });
    expect(res.status).toBe(401);
  });

  it('returns 400 when entries field is missing', async () => {
    const res = await request(app)
      .put(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie())
      .send({});
    expect(res.status).toBe(400);
  });

  it('returns 400 when entries array is empty', async () => {
    const res = await request(app)
      .put(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie())
      .send({ entries: [] });
    expect(res.status).toBe(400);
  });

  it('saves the ranking and returns the entries', async () => {
    mockTransaction();

    const res = await request(app)
      .put(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie())
      .send({ entries: ENTRIES_PAYLOAD });

    expect(res.status).toBe(200);
    expect(res.body.data.year).toBe(YEAR);
    expect(res.body.data.entries).toEqual(ENTRIES_PAYLOAD);
  });

  it('invalidates the analysis cache after saving', async () => {
    mockTransaction();

    await request(app)
      .put(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie())
      .send({ entries: ENTRIES_PAYLOAD });

    expect(vi.mocked(invalidateRankingAnalysisCache)).toHaveBeenCalledWith(USER_ID, YEAR);
  });
});

describe('DELETE /api/rankings/:year', () => {
  it('returns 401 without a cookie', async () => {
    const res = await request(app).delete(`/api/rankings/${YEAR}`);
    expect(res.status).toBe(401);
  });

  it('returns 404 when the ranking does not exist', async () => {
    vi.mocked(prisma.ranking.findUnique).mockResolvedValue(null);

    const res = await request(app)
      .delete(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie());

    expect(res.status).toBe(404);
  });

  it('deletes the ranking and returns success', async () => {
    const existing = { id: 42, userId: USER_ID, year: YEAR, createdAt: new Date(), updatedAt: new Date() };
    vi.mocked(prisma.ranking.findUnique).mockResolvedValue(existing as never);
    vi.mocked(prisma.ranking.delete).mockResolvedValue(existing as never);

    const res = await request(app)
      .delete(`/api/rankings/${YEAR}`)
      .set('Cookie', authCookie());

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
  });
});
