// This file was mostly generated by AI!

import 'dotenv/config';
import { PrismaClient } from "@prisma/client";
import fs from "fs";
import path from "path";
import { PrismaPg } from '@prisma/adapter-pg';

interface Score {
  name: string;
  points: number;
  votes: Record<string, number>;
}

interface Performance {
  contestantId: number;
  running: number;
  place: number;
  scores: Score[];
}

interface RoundData {
  date: string;
  time: string;
  disqualifieds: null | string[];
  performances: Performance[];
}

interface RankedEntry {
  contestantId: number;
  place: number;
  juryPoints: number | null;
  televotePoints: number | null;
  totalPoints: number;
}

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const prisma = new PrismaClient({ adapter });

function getScoreByName(scores: Score[], name: string): Score | undefined {
  return scores.find(s => s.name === name);
}

function extractPointsFromScores(scores: Score[]): {
  juryPoints: number | null;
  televotePoints: number | null;
  totalPoints: number;
} {
  const totalScore = getScoreByName(scores, 'total');
  const juryScore = getScoreByName(scores, 'jury');
  const publicScore = getScoreByName(scores, 'public');

  return {
    juryPoints: juryScore?.points ?? null,
    televotePoints: publicScore?.points ?? null,
    totalPoints: totalScore?.points ?? 0,
  };
}

function buildContestantIdToCountryMap(
  baseDir: string,
  year: number
): Map<number, string> {
  const map = new Map<number, string>();
  const contestantDir = path.join(baseDir, year.toString(), "contestants");

  if (!fs.existsSync(contestantDir)) {
    return map;
  }

  const folders = fs.readdirSync(contestantDir);

  for (const folder of folders) {
    // Folder names are like "0_se", "1_ru", where the number is contestantId
    const match = folder.match(/^(\d+)_(.+)$/);
    if (match) {
      const contestantId = parseInt(match[1], 10);
      const countryCode = match[2].toUpperCase();
      
      // Try to read contestant.json to get the actual country name
      const contestantPath = path.join(contestantDir, folder, "contestant.json");
      if (fs.existsSync(contestantPath)) {
        try {
          const data = JSON.parse(fs.readFileSync(contestantPath, "utf-8"));
          map.set(contestantId, data.country);
        } catch {
          console.warn(`Failed to parse ${folder}/contestant.json, using code instead`);
          map.set(contestantId, countryCode);
        }
      } else {
        map.set(contestantId, countryCode);
      }
    }
  }

  return map;
}

async function seedOfficialResults() {
  const startYear = 2015;
  const endYear = 2025;
  const baseDir = path.join(__dirname, "../../", "data");

  // Delete existing official results
  await prisma.officialResult.deleteMany();

  for (let year = startYear; year <= endYear; year++) {
    const yearStr = year.toString();
    const yearDir = path.join(baseDir, yearStr, "rounds");

    console.log(`\n--- Processing year ${year} ---`);
    
    // Build mapping of contestantId -> country for this year
    const contestantMap = buildContestantIdToCountryMap(baseDir, year);

    // Load round data
    const finalPath = path.join(yearDir, "final.json");
    const semi1Path = path.join(yearDir, "semifinal1.json");
    const semi2Path = path.join(yearDir, "semifinal2.json");

    if (!fs.existsSync(finalPath)) {
      console.log(`No final.json found for ${year}, skipping...`);
      continue;
    }

    const finalData: RoundData = JSON.parse(fs.readFileSync(finalPath, "utf-8"));
    const semi1Data: RoundData | null = fs.existsSync(semi1Path)
      ? JSON.parse(fs.readFileSync(semi1Path, "utf-8"))
      : null;
    const semi2Data: RoundData | null = fs.existsSync(semi2Path)
      ? JSON.parse(fs.readFileSync(semi2Path, "utf-8"))
      : null;

    // Validate that we have performance data
    if (!finalData || !finalData.performances) {
      console.log(`No valid performance data in final.json for ${year}, skipping...`);
      continue;
    }

    // Extract final qualifiers (places 1 to ~26)
    const finalRankings: RankedEntry[] = finalData.performances.map((perf) => ({
      contestantId: perf.contestantId,
      place: perf.place,
      ...extractPointsFromScores(perf.scores),
    }));

    // Extract non-qualifiers from semis (place >= 11)
    const semiNonQualifiers: RankedEntry[] = [];

    if (semi1Data && semi1Data.performances) {
      semi1Data.performances
        .filter(perf => perf.place >= 11)
        .forEach(perf => {
          semiNonQualifiers.push({
            contestantId: perf.contestantId,
            place: perf.place,
            ...extractPointsFromScores(perf.scores),
          });
        });
    }

    if (semi2Data && semi2Data.performances) {
      semi2Data.performances
        .filter(perf => perf.place >= 11)
        .forEach(perf => {
          semiNonQualifiers.push({
            contestantId: perf.contestantId,
            place: perf.place,
            ...extractPointsFromScores(perf.scores),
          });
        });
    }

    // Sort semi non-qualifiers by total points descending
    semiNonQualifiers.sort((a, b) => b.totalPoints - a.totalPoints);

    // Create combined ranking: finals first, then sorted semis
    const finalMaxPlace = Math.max(...finalRankings.map(r => r.place));
    const combinedRanking: RankedEntry[] = [
      ...finalRankings,
      ...semiNonQualifiers.map((entry, index) => ({
        ...entry,
        place: finalMaxPlace + index + 1,
      })),
    ];

    console.log(`Found ${finalRankings.length} finalists and ${semiNonQualifiers.length} non-qualifiers`);
    console.log(`Total rankings to store: ${combinedRanking.length}`);

    // Seed to database
    for (const ranking of combinedRanking) {
      try {
        const country = contestantMap.get(ranking.contestantId);

        if (!country) {
          console.warn(`Could not find country for contestantId ${ranking.contestantId} in year ${year}`);
          continue;
        }

        const entry = await prisma.entry.findUnique({
          where: {
            year_country: {
              year,
              country,
            },
          },
        });

        if (!entry) {
          console.warn(`Entry not found for ${country} (${year})`);
          continue;
        }

        // Create official result
        await prisma.officialResult.create({
          data: {
            entryId: entry.id,
            rank: ranking.place,
            juryPoints: ranking.juryPoints,
            televotePoints: ranking.televotePoints,
            totalPoints: ranking.totalPoints,
          },
        });

        console.log(`✓ Seeded: ${country} - Rank ${ranking.place}`);
      } catch (error) {
        console.error(`Error seeding contestantId ${ranking.contestantId} for year ${year}:`, error);
      }
    }
  }

  console.log(`\n✅ Official results seeding complete!`);
}

seedOfficialResults()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => await prisma.$disconnect());
