// Caching logic was generated by AI

import { prisma } from '../config/database';
import type { OfficialResultResponse } from '../types';
import { createHttpError } from '../utils/httpError';
import { getOfficialResultsByYearData } from './officialResults';
import { generateRankingAnalysis } from './rankingAnalysis';

const ANALYSIS_CACHE_TTL_MS = 1000 * 60 * 60 * 12;

type CachedAnalysis = {
  analysis: string;
  expiresAt: number;
};

const rankingAnalysisCache = new Map<string, CachedAnalysis>();

const getCachedAnalysis = (cacheKey: string): string | null => {
  const cached = rankingAnalysisCache.get(cacheKey);

  if (!cached) {
    return null;
  }

  if (cached.expiresAt <= Date.now()) {
    rankingAnalysisCache.delete(cacheKey);
    return null;
  }

  return cached.analysis;
};

const setCachedAnalysis = (cacheKey: string, analysis: string): void => {
  rankingAnalysisCache.set(cacheKey, {
    analysis,
    expiresAt: Date.now() + ANALYSIS_CACHE_TTL_MS,
  });
};

const buildOfficialResultsSignature = (officialResults: OfficialResultResponse[]): string => {
  return officialResults
    .map((result) => (
      `${result.entryId}:${result.rank}:${result.juryPoints ?? 'n'}:${result.televotePoints ?? 'n'}:${result.totalPoints}:${result.finalist ? 1 : 0}`
    ))
    .join('|');
};

export const invalidateRankingAnalysisCache = (userId: number, year: number): void => {
  const prefix = `${userId}:${year}:`;

  for (const key of rankingAnalysisCache.keys()) {
    if (key.startsWith(prefix)) {
      rankingAnalysisCache.delete(key);
    }
  }
};

export const getRankingAnalysisForYear = async (userId: number, year: number): Promise<string> => {
  const ranking = await prisma.ranking.findUnique({
    where: {
      userId_year: {
        userId,
        year,
      },
    },
    include: {
      entries: {
        orderBy: { position: 'asc' },
        select: {
          entryId: true,
          position: true,
          entry: {
            select: {
              country: true,
              artist: true,
              song: true,
            },
          },
        },
      },
    },
  });

  if (!ranking) {
    throw createHttpError(404, 'Ranking not found');
  }

  const userRanking = ranking.entries.map((entry) => ({
    position: entry.position,
    country: entry.entry.country,
    artist: entry.entry.artist,
    song: entry.entry.song,
  }));

  const officialResults: OfficialResultResponse[] = await getOfficialResultsByYearData(year);
  const officialResultsSignature = buildOfficialResultsSignature(officialResults);
  const cacheKey = `${userId}:${year}:${ranking.updatedAt.getTime()}:${officialResultsSignature}`;
  const cachedAnalysis = getCachedAnalysis(cacheKey);

  if (cachedAnalysis) {
    return cachedAnalysis;
  }

  const officialResultsForAnalysis = officialResults.map((result) => ({
    rank: result.rank,
    country: result.entry.country,
    artist: result.entry.artist,
    song: result.entry.song,
    juryPoints: result.juryPoints,
    televotePoints: result.televotePoints,
    totalPoints: result.totalPoints,
    finalist: Boolean(result.finalist),
  }));

  const analysis = await generateRankingAnalysis(year, userRanking, officialResultsForAnalysis);
  setCachedAnalysis(cacheKey, analysis);

  return analysis;
};
