// this file was mostlyy generated by AI

import { prisma } from '../config/database';
import { createHttpError } from '../utils/httpError';
import type { OfficialResultResponse, YearOverviewResponse } from '../types';
import { getOfficialResultsByYearData } from './officialResults';

export const getYearOverviewData = async (year: number): Promise<YearOverviewResponse> => {
  const [contest, results] = await Promise.all([
    prisma.contest.findUnique({ where: { year } }),
    getOfficialResultsByYearData(year),
  ]);

  if (!contest) {
    throw createHttpError(404, `Contest for year ${year} not found`);
  }

  return {
    contest,
    top3: results.slice(0, 3),
    winner: results[0] ?? null,
    juryWinner: getWinnerByPoints(results, 'juryPoints'),
    televoteWinner: getWinnerByPoints(results, 'televotePoints'),
    contestantsCount: results.length,
  };
};

const getWinnerByPoints = (
  results: OfficialResultResponse[],
  pointType: 'juryPoints' | 'televotePoints'
): OfficialResultResponse | null => {
  const candidates = results.filter((result) => result[pointType] !== null);

  if (candidates.length === 0) {
    return null;
  }

  return candidates.reduce((best, current) => {
    const currentPoints = current[pointType] ?? -1;
    const bestPoints = best[pointType] ?? -1;
    return currentPoints > bestPoints ? current : best;
  });
};
