// this file was mostly generated by AI

import { describe, it, expect, beforeEach } from 'vitest';
import {
  sortAndPopulateEntries,
  mapEntriesByRankingOrder,
  mapEntriesToRankingFormat,
  saveDraftToLocalStorage,
  loadDraftFromLocalStorage,
  clearDraftFromLocalStorage,
} from '../rankingHelper';
import type { Entry } from '@/types/entry';
import type { RankingEntry } from '@/types/ranking';

const makeEntry = (id: number): Entry => ({
  id,
  year: 2024,
  country: `Country${id}`,
  artist: `Artist${id}`,
  song: `Song${id}`,
  youtubeUrl: null,
});

const rank = (entryId: number, position: number): RankingEntry => ({ entryId, position });

const ENTRIES = [makeEntry(1), makeEntry(2), makeEntry(3), makeEntry(4)];

describe('sortAndPopulateEntries', () => {
  it('returns entries sorted by position', () => {
    const ranking = [rank(3, 0), rank(1, 1), rank(2, 2)];
    const result = sortAndPopulateEntries(ENTRIES, ranking);
    expect(result.map((e) => e.id)).toEqual([3, 1, 2]);
  });

  it('handles out-of-order positions', () => {
    const ranking = [rank(2, 2), rank(3, 0), rank(1, 1)];
    const result = sortAndPopulateEntries(ENTRIES, ranking);
    expect(result.map((e) => e.id)).toEqual([3, 1, 2]);
  });

  it('returns empty array when no ranking entries given', () => {
    expect(sortAndPopulateEntries(ENTRIES, [])).toEqual([]);
  });
});

describe('mapEntriesByRankingOrder', () => {
  it('puts ranked entries first, unranked entries after', () => {
    const ranking = [rank(3, 0), rank(1, 1)];
    const { entriesInOrder } = mapEntriesByRankingOrder(ENTRIES, ranking);
    expect(entriesInOrder[0].id).toBe(3);
    expect(entriesInOrder[1].id).toBe(1);
    // entries 2 and 4 come after in some order, but they must both be present
    const remainingIds = entriesInOrder.slice(2).map((e) => e.id);
    expect(remainingIds).toContain(2);
    expect(remainingIds).toContain(4);
  });

  it('returns correct rankedCount', () => {
    const ranking = [rank(1, 0), rank(2, 1)];
    const { rankedCount } = mapEntriesByRankingOrder(ENTRIES, ranking);
    expect(rankedCount).toBe(2);
  });

  it('returns rankedCount of 0 and all entries unranked when no ranking given', () => {
    const { entriesInOrder, rankedCount } = mapEntriesByRankingOrder(ENTRIES, []);
    expect(rankedCount).toBe(0);
    expect(entriesInOrder).toHaveLength(ENTRIES.length);
  });
});

describe('mapEntriesToRankingFormat', () => {
  it('maps the first rankedCount entries to { entryId, position } with 0-based positions', () => {
    const result = mapEntriesToRankingFormat(ENTRIES, 3);
    expect(result).toEqual([
      { entryId: 1, position: 0 },
      { entryId: 2, position: 1 },
      { entryId: 3, position: 2 },
    ]);
  });

  it('excludes entries beyond rankedCount', () => {
    const result = mapEntriesToRankingFormat(ENTRIES, 2);
    expect(result).toHaveLength(2);
    expect(result.map((r) => r.entryId)).toEqual([1, 2]);
  });

  it('returns empty array when rankedCount is 0', () => {
    expect(mapEntriesToRankingFormat(ENTRIES, 0)).toEqual([]);
  });
});

describe('localStorage draft functions', () => {
  beforeEach(() => {
    localStorage.clear();
  });

  it('loadDraftFromLocalStorage returns null when nothing is saved', () => {
    expect(loadDraftFromLocalStorage(2024, 1)).toBeNull();
  });

  it('loadDraftFromLocalStorage returns null for a different user', () => {
    saveDraftToLocalStorage(2024, ENTRIES, 2, 1);
    expect(loadDraftFromLocalStorage(2024, 2)).toBeNull();
  });

  it('save and load round-trip works for a logged-in user', () => {
    saveDraftToLocalStorage(2024, ENTRIES, 2, 1);
    const loaded = loadDraftFromLocalStorage(2024, 1);
    expect(loaded).toEqual([
      { entryId: 1, position: 0 },
      { entryId: 2, position: 1 },
    ]);
  });

  it('save and load round-trip works for a guest', () => {
    saveDraftToLocalStorage(2024, ENTRIES, 1, null);
    const loaded = loadDraftFromLocalStorage(2024, null);
    expect(loaded).toEqual([{ entryId: 1, position: 0 }]);
  });

  it('loadDraftFromLocalStorage returns null for corrupted data', () => {
    localStorage.setItem('draft_1_2024', 'not valid json{{');
    expect(loadDraftFromLocalStorage(2024, 1)).toBeNull();
  });

  it('clearDraftFromLocalStorage removes the saved draft', () => {
    saveDraftToLocalStorage(2024, ENTRIES, 2, 1);
    clearDraftFromLocalStorage(2024, 1);
    expect(loadDraftFromLocalStorage(2024, 1)).toBeNull();
  });
});
