// This file was mostly generated by AI

import { NextFunction, Request, Response } from 'express';
import jwt, { JwtPayload } from 'jsonwebtoken';
import { createHttpError } from '../utils/httpError';

type AuthTokenPayload = JwtPayload & {
  sub?: string | number;
};

const getTokenFromCookies = (cookies: unknown): string | null => {
  if (typeof cookies !== 'object' || cookies === null) {
    return null;
  }

  const token = (cookies as Record<string, unknown>).token;

  if (typeof token !== 'string' || token.length === 0) {
    return null;
  }

  return token;
};

export const requireAuth = (req: Request, res: Response, next: NextFunction) => {
  const token = getTokenFromCookies(req.cookies);

  if (!token) {
    return next(createHttpError(401, 'Unauthorized'));
  }

  const secret = process.env.JWT_SECRET;

  if (!secret) {
    return next(createHttpError(500, 'JWT_SECRET is not configured'));
  }

  try {
    const decoded = jwt.verify(token, secret) as AuthTokenPayload;
    const userId = Number(decoded.sub);

    if (!Number.isInteger(userId)) {
      return next(createHttpError(401, 'Invalid token'));
    }

    res.locals.userId = userId;
    return next();
  } catch {
    return next(createHttpError(401, 'Invalid or expired token'));
  }
};
