// This file was generated by AI

const COUNTRY_NAME_OVERRIDES: Record<string, string> = {
	AL: 'Albania',
	AD: 'Andorra',
	AM: 'Armenia',
	AU: 'Australia',
	AT: 'Austria',
	AZ: 'Azerbaijan',
	BY: 'Belarus',
	BE: 'Belgium',
	BA: 'Bosnia and Herzegovina',
	BG: 'Bulgaria',
	HR: 'Croatia',
	CY: 'Cyprus',
	CZ: 'Czechia',
	DK: 'Denmark',
	EE: 'Estonia',
	FI: 'Finland',
	FR: 'France',
	GE: 'Georgia',
	DE: 'Germany',
	GR: 'Greece',
	HU: 'Hungary',
	IS: 'Iceland',
	IE: 'Ireland',
	IL: 'Israel',
	IT: 'Italy',
	KZ: 'Kazakhstan',
	LV: 'Latvia',
	LT: 'Lithuania',
	LU: 'Luxembourg',
	MT: 'Malta',
	MD: 'Moldova',
	MC: 'Monaco',
	ME: 'Montenegro',
	MA: 'Morocco',
	NL: 'Netherlands',
	MK: 'North Macedonia',
	NO: 'Norway',
	PL: 'Poland',
	PT: 'Portugal',
	RO: 'Romania',
	RU: 'Russia',
	SM: 'San Marino',
	RS: 'Serbia',
	CS: 'Serbia and Montenegro',
	SK: 'Slovakia',
	SI: 'Slovenia',
	ES: 'Spain',
	SE: 'Sweden',
	CH: 'Switzerland',
	TR: 'Turkey',
	UA: 'Ukraine',
	GB: 'United Kingdom',
	'GB-WLS': 'Wales',
	YU: 'Yugoslavia',
};

const regionDisplayNames = new Intl.DisplayNames(['en'], { type: 'region' });
const toUpperName = (value: string) => value.toLocaleUpperCase('en');

export function getCountryName(countryCode: string): string {
	const normalizedCode = countryCode.trim().toUpperCase();

	if (!normalizedCode) {
		return toUpperName(countryCode);
	}

	const override = COUNTRY_NAME_OVERRIDES[normalizedCode];
	if (override) {
		return toUpperName(override);
	}

	const fromIntl = regionDisplayNames.of(normalizedCode);
	if (fromIntl) {
		return toUpperName(fromIntl);
	}

	return normalizedCode;
}

export { COUNTRY_NAME_OVERRIDES };
