// this file was generated by AI

export function getErrorMessage(error: Error | null): string {
  if (!error?.message) return "Something went wrong. Please try again.";

  const msg = error.message.toLowerCase();

  if (msg.includes('500') || msg.includes('502') || msg.includes('503')) {
    return "The server is having trouble. Please try again in a moment.";
  }
  if (msg.includes('400') || msg.includes('404')) {
    return "Something went wrong with your request. Please refresh the page.";
  }
  if (msg.includes('timeout') || msg.includes('took too long')) {
    return "The request took too long. Please try again.";
  }
  if (msg.includes('fetch') && msg.includes('failed')) {
    return "Could not connect to the server. Check your connection and try again.";
  }

  return error.message;
}