// this file was generated by AI

export const getErrorMessage = (error: Error | null): string => {
  if (!error) {
    return 'Something went wrong. Please try again.';
  }

  const message = error.message.toLowerCase();

  if (message.includes('status 500') || message.includes('status 502') || message.includes('status 503')) {
    return 'The server is having trouble. Please try again in a moment.';
  }

  if (message.includes('status 404') || message.includes('status 400')) {
    return 'Something went wrong with your request. Please refresh the page.';
  }

  if (message.includes('timeout') || message.includes('took too long')) {
    return 'The request took too long. Please try again.';
  }

  if (message.includes('failed') && message.includes('fetch')) {
    return 'Could not connect to the server. Check your connection and try again.';
  }

  return 'Something went wrong. Please try again.';
};
