import type { Entry } from "@/types/entry";
import type { RankingEntry } from "@/types/ranking";


const mapEntriesByRankingOrder = (entries: Entry[], rankingEntries: RankingEntry[]): { initialEntries: Entry[]; rankedCount: number } => {
  // this function was generated by AI
  const entriesById = new Map(entries.map((entry) => [entry.id, entry]));

  const rankedEntries = rankingEntries
    .slice()
    .sort((left, right) => left.position - right.position)
    .map((rankingEntry) => entriesById.get(rankingEntry.entryId))
    .filter((entry): entry is Entry => Boolean(entry));

  const rankedIds = new Set(rankedEntries.map((entry) => entry.id));
  const unrankedEntries = entries.filter((entry) => !rankedIds.has(entry.id));

  return { initialEntries: [...rankedEntries, ...unrankedEntries], rankedCount: rankedEntries.length };
};

const mapEntriesToRankingFormat = (entries: Entry[], rankedCount: number): { entryId: number; position: number }[] => {
  return entries.slice(0, rankedCount).map((entry, index) => ({
    entryId: entry.id,
    position: index,
  }));
};

export { mapEntriesByRankingOrder, mapEntriesToRankingFormat };