import type { Entry } from "@/types/entry";
import type { RankingEntry } from "@/types/ranking";


const mapEntriesByRankingOrder = (entries: Entry[], rankingEntries: RankingEntry[]): { entriesInOrder: Entry[]; rankedCount: number } => {
  const rankedEntries = sortEntriesByRanking(entries, rankingEntries);
  
  const rankedIds = new Set(rankedEntries.map((entry) => entry.id));
  const unrankedEntries = entries.filter((entry) => !rankedIds.has(entry.id));
  
  return { entriesInOrder: [...rankedEntries, ...unrankedEntries], rankedCount: rankedEntries.length };
};

const sortEntriesByRanking = (entries: Entry[], rankingEntries: RankingEntry[]): Entry[] => {
  // this function was generated by AI
  const entryMap = new Map(entries.map((e) => [e.id, e]));
  return rankingEntries
    .slice()
    .sort((a, b) => a.position - b.position)
    .map((r) => entryMap.get(r.entryId))
    .filter((e): e is Entry => Boolean(e));
};

const mapEntriesToRankingFormat = (entries: Entry[], rankedCount: number): RankingEntry[] => {
  return entries.slice(0, rankedCount).map((entry, index) => ({
    entryId: entry.id,
    position: index,
  }));
};

const saveDraftToLocalStorage = (year: number, entries: Entry[], rankedCount: number, userId: number | null) => {
  const key = userId ? `draft_${userId}_${year}` : `draft_guest_${year}`;
  const rankedEntryIds = mapEntriesToRankingFormat(entries, rankedCount);
  localStorage.setItem(key, JSON.stringify({ rankedEntryIds }));
};

const clearDraftFromLocalStorage = (year: number, userId: number | null) => {
  const key = userId ? `draft_${userId}_${year}` : `draft_guest_${year}`;
  localStorage.removeItem(key);
};

const loadDraftFromLocalStorage = (year: number, userId: number | null): RankingEntry[] | null => {
  const key = userId ? `draft_${userId}_${year}` : `draft_guest_${year}`;
  const stored = localStorage.getItem(key);
  if (!stored) return null;
  try {
    const parsed = JSON.parse(stored);
    return parsed.rankedEntryIds || null;
  } catch {
    return null;
  }
};

export { mapEntriesByRankingOrder, mapEntriesToRankingFormat, saveDraftToLocalStorage, clearDraftFromLocalStorage, loadDraftFromLocalStorage, sortEntriesByRanking };