// This file was generated by AI

export function getYoutubeThumbnailUrl(embedUrl: string | null): string | null {
  if (!embedUrl) {
    return null;
  }

  try {
    const url = new URL(embedUrl);
    const embedMatch = url.pathname.match(/\/embed\/([^/?#]+)/);
    const videoId = embedMatch?.[1];

    if (!videoId) {
      return null;
    }

    return `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
  } catch {
    return null;
  }
}
